name: User Info Tests

on:
  push:
    branches:
      - dev
    paths:
      - "user_info/**"
  pull_request:
    branches:
      - dev
    paths:
      - "user_info/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r user_info/requirements.txt

      - name: Run pytest
        run: |
          pytest user_info/tests/
